from flask import Flask, render_template, request, send_file
import zipfile
import pdfplumber
import pandas as pd
import re
import io
import os
import traceback

app = Flask(__name__)

UPLOAD_FOLDER = "uploads"
OUTPUT_FOLDER = "outputs"

os.makedirs(UPLOAD_FOLDER, exist_ok=True)
os.makedirs(OUTPUT_FOLDER, exist_ok=True)


@app.route("/")
def home():
    return render_template("index.html")


@app.route("/test")
def test():
    return "Flask is working!"


@app.route("/upload", methods=["POST"])
def upload():
    try:
        if "zipfile" not in request.files:
            return "No ZIP file uploaded"

        file = request.files["zipfile"]

        if file.filename == "":
            return "No file selected"

        zip_path = os.path.join(UPLOAD_FOLDER, file.filename)
        file.save(zip_path)

        rows = []
        skipped = []

        with zipfile.ZipFile(zip_path, "r") as z:

            pdf_files = [
                f for f in z.namelist()
                if f.lower().endswith(".pdf")
            ]

            for pdf_name in pdf_files:

                ps_match = re.search(r"PS-(\d+)", pdf_name)

                ps_no = ps_match.group(1) if ps_match else ""

                try:
                    pdf_bytes = io.BytesIO(z.read(pdf_name))

                    with pdfplumber.open(pdf_bytes) as pdf:

                        for page in pdf.pages:

                            text = page.extract_text()

                            if not text:
                                continue

                            for line in text.split("\n"):

                                line = line.strip()

                                if not line:
                                    continue

                                if (
                                    line.startswith("Date of Generation")
                                    or line.startswith("View Enumeration")
                                    or line.startswith("AC:")
                                    or line.startswith("S.No.")
                                    or line.startswith("Note:")
                                    or "Generated by" in line
                                    or "Page" in line
                                ):
                                    continue

                                m = re.match(
                                    r'^(\d+)\s+'
                                    r'(\d+)\s+'
                                    r'([A-Z0-9\/]+)\s+'
                                    r'(.+?)\s+'
                                    r'(.+?)\s+'
                                    r'\((Father|Husband|Mother)\)\s+'
                                    r'(Death|Permanently Shifted|Already enrolled|Untraceable\/Absent|Duplicate)',
                                    line,
                                    re.I
                                )

                                if m:
                                    rows.append({
                                        "S.No": m.group(1),
                                        "Serial No": m.group(2),
                                        "EPIC Number": m.group(3),
                                        "Elector Name": m.group(4).strip(),
                                        "Relative Details": m.group(5).strip(),
                                        "Relation Type": m.group(6).strip(),
                                        "Uncollectable Reason": m.group(7).strip(),
                                        "PS No": ps_no
                                    })
                                else:
                                    skipped.append(line)

                except Exception as e:
                    print(f"Error processing {pdf_name}: {e}")

        df = pd.DataFrame(rows)

        if df.empty:
            return "No records extracted."

        df["PS No"] = pd.to_numeric(df["PS No"], errors="coerce")

        output_file = os.path.join(
            OUTPUT_FOLDER,
            "Final_Voter_List.xlsx"
        )

        skipped_file = os.path.join(
            OUTPUT_FOLDER,
            "skipped_records.txt"
        )

        with open(skipped_file, "w", encoding="utf-8") as f:
            for item in skipped:
                f.write(item + "\n")

        with pd.ExcelWriter(output_file) as writer:

            sheet1 = df[
                (
                    ((df["PS No"] >= 1) & (df["PS No"] <= 80))
                    |
                    ((df["PS No"] >= 145) & (df["PS No"] <= 165))
                    |
                    ((df["PS No"] >= 208) & (df["PS No"] <= 240))
                )
            ]

            sheet2 = df[
                (df["PS No"] >= 81)
                &
                (df["PS No"] <= 144)
            ]

            sheet1.to_excel(
                writer,
                sheet_name="Sheet1",
                index=False
            )

            sheet2.to_excel(
                writer,
                sheet_name="Sheet2",
                index=False
            )

        return send_file(
            output_file,
            as_attachment=True,
            download_name="Final_Voter_List.xlsx"
        )

    except Exception as e:
        print(traceback.format_exc())
        return f"ERROR: {str(e)}", 500


if __name__ == "__main__":
    app.run(debug=True)
