import zipfile
import pdfplumber
import pandas as pd
import re
import io

zip_path = input("Enter ZIP path: ")

rows = []
skipped = []

with zipfile.ZipFile(zip_path, "r") as z:

    pdf_files = [f for f in z.namelist() if f.lower().endswith(".pdf")]

    print("PDF Files Found:", len(pdf_files))

    for pdf_name in pdf_files:

        print("Reading:", pdf_name)

        ps_match = re.search(r"PS-(\d+)", pdf_name)
        ps_no = ps_match.group(1) if ps_match else ""

        try:

            pdf_bytes = io.BytesIO(z.read(pdf_name))

            with pdfplumber.open(pdf_bytes) as pdf:

                for page in pdf.pages:

                    text = page.extract_text()

                    if not text:
                        continue

                    lines = text.split("\n")

                    for line in lines:

                        line = line.strip()

                        # Skip headers / footers
                        if (
                            not line
                            or line.startswith("Date of Generation")
                            or line.startswith("View Enumeration")
                            or line.startswith("AC:")
                            or line.startswith("S.No.")
                            or line.startswith("Note:")
                            or "Generated by" in line
                            or line.startswith("Page ")
                        ):
                            continue

                        m = re.match(
                            r'^(\d+)\s+'                          # S.No
                            r'(\d+)\s+'                          # Serial No
                            r'([A-Z0-9\/]+)\s+'                  # EPIC
                            r'(.+?)\s+'                          # Elector Name
                            r'(.+?)\s+'                          # Relative Name
                            r'\((Father|Husband|Mother)\)\s+'    # Relation
                            r'(.+)$',                            # Reason
                            line,
                            re.I
                        )

                        if m:

                            rows.append({
                                "S.No": m.group(1),
                                "Serial No": m.group(2),
                                "EPIC Number": m.group(3),
                                "Elector Name": m.group(4).strip(),
                                "Relative Details": m.group(5).strip(),
                                "Relation Type": m.group(6).strip(),
                                "Uncollectable Reason": m.group(7).strip(),
                                "PS No": ps_no
                            })

                        else:
                            skipped.append(line)

        except Exception as e:
            print("ERROR:", pdf_name, e)

df = pd.DataFrame(rows)

# Save skipped records for analysis
with open("skipped_records.txt", "w", encoding="utf-8") as f:
    for item in skipped:
        f.write(item + "\n")

print("Total Records:", len(df))

# Convert PS No to numeric
df["PS No"] = pd.to_numeric(df["PS No"], errors="coerce")

with pd.ExcelWriter("Final_Voter_List.xlsx", engine="openpyxl") as writer:

    sheet1 = df[
        (
            (df["PS No"] >= 1) &
            (df["PS No"] <= 80)
        )
        |
        (
            (df["PS No"] >= 145) &
            (df["PS No"] <= 165)
        )
        |
        (
            (df["PS No"] >= 208) &
            (df["PS No"] <= 240)
        )
    ]

    sheet2 = df[
        (df["PS No"] >= 81)
        &
        (df["PS No"] <= 144)
    ]

    sheet1.to_excel(
        writer,
        sheet_name="Sheet1",
        index=False
    )

    sheet2.to_excel(
        writer,
        sheet_name="Sheet2",
        index=False
    )

print("Done!")
print("Excel Saved: Final_Voter_List.xlsx")
print("Sheet1 Records:", len(sheet1))
print("Sheet2 Records:", len(sheet2))
print("Total Records:", len(df))
print("Skipped Records:", len(skipped))

